sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: JaZX7mXvJs3fZaihKTvSpXZOxsIcMvsigVk7M9zhCdBwzONh9S/mmlYnqb37iS3rfXe6IEdrWZTUNG4W3qH3cOBQVX8PglYBOeyLGHrAZHskmDSbp2URYC+jYea61kCymRfRThxN3mB2QDknPPO3sloVoRIhisnsrAEwy4nwlPFyuhKDZkcxldFt8NDMxt9YdV/LGs39e6Fj3dBU6fPgPR+ADm+RVnM2IbrPG7BRVR0PjvVjYZKNMvY+prXWXBISF2LUWHdfaVoBHxBvxpAPOSOxvd4epM55NquJwRJ4wUJNaL8qu7bjWOguvHmb8//bMx5Sehw758mK3zIxPfWybjY8BM1r76HvNFL/3PocNnbY+oX5siHIaH2y503fIEK6QcaAJUMJPdL83PKsw4lVU+ngdOSPiNV16Jtxa8Jhshh1g5jd34dP6qKDAJVEjxXmZhO+Z9iD1JNuvZEHSsTYv+2bvAQfrZpv7EbqiH618Ch7lqPJ7gnPE1o+NnwsX1+RUjFF1sHvnJ3K4dpJY73J2CxPi6A9GYcz6mgD+5b2zva/pE5emLzag3mnPsHc10fMC6oMt/9gAmib58h57d0NC2y5L57gr6/JPmYUM/QXBF5eP4qCvQiBvRyJFjnxPqdYCLRbao3xMw2A1+5U2ZclHA8yTplMfyZ8hfWcUn0L2wY=
  - secure: ikK4prKVcTGD/8BaZuczaMwz5tG1LF8DwrGhy02psrdE5yZ98tKcqJ6F5Qq2o5qarcsm9xXxPpIweo5oxas9rMOGHUwnhGqKMRLoDW75DKS+RcfaRQlAbMkKSco8FpRoE5C0MWmoyRSjiU5+ssaLOwoZuaXqLReY+DLbKzuLHz5Sz0MEhn51CmAFV9Jt2Ai9Ak0ZAumG31xNXvow+fwOISumh+xgeXxF4K1BcyF12nc7VEjWsUJymrTNQOJPTbEBEu2mNN+QWz3hTaZH/R999v5IVkzC7RdqiE5poM1rty90V8UgtdVyVPTOnIjaDGfWL3KeimHruOd7oxUbpCiWCC6EBA+j6LR9o4g10tzUVfbuEMuzH9we4exy1odSB4tOGWvXUT/cHWaCf6qK9AAxe1IIN9tocxzatecWh4xRC9FHJ64dXDw1My0owvLv82mE64KL0fS6GDkEKKOFejSBCZVTT21hof9ispqztPnoxhcdcMbOZDu7kBUcIwCHL4GA4zjnkdssX8tlTd6Q45M2DTfIL/pQTJk3+Ann0gBFpduT6PwbgZzu4qAP4ww/a98l8zKXfeJE2dBVNdwm+TqhAvkJ3q7JrEQoyLUkTrSILgSUvJOlXxRb8/zHzPeelIepkZXiilYFoOpmgPy3l6y6FoRjvG3pVjojdi1d5UcBDj4=
