sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: JaZX7mXvJs3fZaihKTvSpXZOxsIcMvsigVk7M9zhCdBwzONh9S/mmlYnqb37iS3rfXe6IEdrWZTUNG4W3qH3cOBQVX8PglYBOeyLGHrAZHskmDSbp2URYC+jYea61kCymRfRThxN3mB2QDknPPO3sloVoRIhisnsrAEwy4nwlPFyuhKDZkcxldFt8NDMxt9YdV/LGs39e6Fj3dBU6fPgPR+ADm+RVnM2IbrPG7BRVR0PjvVjYZKNMvY+prXWXBISF2LUWHdfaVoBHxBvxpAPOSOxvd4epM55NquJwRJ4wUJNaL8qu7bjWOguvHmb8//bMx5Sehw758mK3zIxPfWybjY8BM1r76HvNFL/3PocNnbY+oX5siHIaH2y503fIEK6QcaAJUMJPdL83PKsw4lVU+ngdOSPiNV16Jtxa8Jhshh1g5jd34dP6qKDAJVEjxXmZhO+Z9iD1JNuvZEHSsTYv+2bvAQfrZpv7EbqiH618Ch7lqPJ7gnPE1o+NnwsX1+RUjFF1sHvnJ3K4dpJY73J2CxPi6A9GYcz6mgD+5b2zva/pE5emLzag3mnPsHc10fMC6oMt/9gAmib58h57d0NC2y5L57gr6/JPmYUM/QXBF5eP4qCvQiBvRyJFjnxPqdYCLRbao3xMw2A1+5U2ZclHA8yTplMfyZ8hfWcUn0L2wY=
  - secure: ikK4prKVcTGD/8BaZuczaMwz5tG1LF8DwrGhy02psrdE5yZ98tKcqJ6F5Qq2o5qarcsm9xXxPpIweo5oxas9rMOGHUwnhGqKMRLoDW75DKS+RcfaRQlAbMkKSco8FpRoE5C0MWmoyRSjiU5+ssaLOwoZuaXqLReY+DLbKzuLHz5Sz0MEhn51CmAFV9Jt2Ai9Ak0ZAumG31xNXvow+fwOISumh+xgeXxF4K1BcyF12nc7VEjWsUJymrTNQOJPTbEBEu2mNN+QWz3hTaZH/R999v5IVkzC7RdqiE5poM1rty90V8UgtdVyVPTOnIjaDGfWL3KeimHruOd7oxUbpCiWCC6EBA+j6LR9o4g10tzUVfbuEMuzH9we4exy1odSB4tOGWvXUT/cHWaCf6qK9AAxe1IIN9tocxzatecWh4xRC9FHJ64dXDw1My0owvLv82mE64KL0fS6GDkEKKOFejSBCZVTT21hof9ispqztPnoxhcdcMbOZDu7kBUcIwCHL4GA4zjnkdssX8tlTd6Q45M2DTfIL/pQTJk3+Ann0gBFpduT6PwbgZzu4qAP4ww/a98l8zKXfeJE2dBVNdwm+TqhAvkJ3q7JrEQoyLUkTrSILgSUvJOlXxRb8/zHzPeelIepkZXiilYFoOpmgPy3l6y6FoRjvG3pVjojdi1d5UcBDj4=
  - secure: vgsUKO6laRT3mZn5Yc1p33xp94uTIt+3d4I0bNz5ro6Odgxu0MVG7LKAIlcJmVt7sRpkRo7c2kRmNUtS9CsM6P3PQQ3pnvQXLRamQP4A243b3SrX7CRVS4F89V63WKPhdoorbZE6EofMgwwfH6MlXLKw/JRSzcfqAB/LqzZO6wIz59947NHbzy58YUkpIrZL+BnV4yq8rixDqtYpSm+sCJLFC8eaM/DCBwH2/gj9rSMgXtraKZYuOJhN+2dnbPZxefjVsRZvIX55xKePNRhpNgzxpqEVcDYM2qObG9la84EP+/vojtJpM0EGiT5MTIdz2jPgWKQotyi216UwaRYe65cv6uuMqn/2+bXSNUryS62ZQ0fl65be8/Ik9SxG3+hZWYggurVFfzm+97CKGSEJzMRKYZn2dcYhTja6oJsxF+ftDFQtDXorHs5LclvO2T177DIU4KTu1a0YcmYkbpk3EgOTbWTAb1pRNRdnkLQkzdrOdaGOJMcKuaYOl5fXpeVas8WPM5hgjUUIcpfuxea5W+SmXQjbgrOuUKBwWjy0sCjsLLGLMjeznDxDioWVqVCZoYP8VBI6KmvGeX4Y69r+38tuyVSGndf8+Dqxf+Zj70lurkGOr7cKPsqT+gUj4yGT6CTmcPQ6P/iJmla7PSVBhgru5tX+Z7K9Iwh3TaR6ozQ=
  - secure: X5k1k/KMsR8S5P5dOd5jUmeP3aDQrIeyBrjyo8ytdtmOQ/WbeAX+cSWn2k8+GKgQC/h2eDuX8VB4UTJ4tupJ46GvYtvE3oWaM1Ng3wi26BiRNiM0IQZygn2PfTx2sxdTs+WIjBUUXglUs31sq5o/BRQnnzVgfTHOCbLIhcYh294w1SKXV+685R6bTaAwVRbOLxxXNvAU2OLg3lbg0P6aLt2921RCb0mmNl5KaqAyIyO0odY63BfDiaRVr4EMWbQZVzxkLoo8bDbvBQ81Q5t/QqX1oAy8g+0O+fkRWXFxIPfFLJqgT1MPf+CbR6gsjLRsR7eMFqecIl5SNGTaHxSY4Hsk4tVoOZR1Eyu44PWBfAPTpRZBHwn7yIKcgk5TwI0Hpa74Xh/GoehMxhhZhBMnO+jH7QkQjHQ+5Z5zi3UR4ZOumFjJT1HIaMXNVfKCo9UOMplBQGf/tjWZTiy0dFXnttDgxSykW95h/2eNYAAwzA3RvWZngpTJV5EGj+VFaU5s9R4cDUjXiiFRuZsHHhxL/WL5zEYwBxMbofXoQVOq1kpfN7kCzIfyYbLJP+h6PJLHE+X3o0oMa9It5y9m9qqnDM0XE4RgaprXZn5f6046L4Pt5D+H0cbh6vgZeI5RZEzMqrq1wW7+lXYdB5P2zeh89i2WrQ4tRhWEBy5mM0wPpDk=
